name: CI workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os.name }}
    strategy:
      matrix:
        deno-version: [v1.x]
        # TODO: fix tests in windows
        os:
          - name: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - name: macOS-latest
            target: x86_64-apple-darwin

    steps:
      - uses: actions/checkout@v2

      - name: Use Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Check formatting
        run: deno fmt --check -c deno.json

      - name: Analyze code
        run: deno lint -c deno.json

      - name: Run unit and integration tests
        run: deno test --lock=lock.json --unstable --allow-read --allow-write -A --coverage=cov --doc

      - name: Generate coverage report
        # Only want to generate this once
        if: ${{ matrix.os.name == 'ubuntu-latest' }}
        run: deno coverage --lcov cov > cov.lcov

      - name: Compile executable for target ${{ matrix.os.target }}
        run: deno compile --lock=lock.json --unstable --allow-read --allow-write src/hello-gen.ts --target ${{ matrix.os.target }}
