name: CI workflow

on: push

jobs:
  test:
    runs-on: ${{ matrix.os.name }}
    strategy:
      matrix:
        deno-version: [v1.x]
        os:
          - name: ubuntu-latest
            platform: linux
            cpu: amd64
            target: x86_64-unknown-linux-gnu
          - name: macOS-latest
            platform: darwin
            cpu: amd64
            target: x86_64-apple-darwin
          - name: windows-latest
            platform: windows
            cpu: amd64
            target: x86_64-pc-windows-msvc

    steps:
      - uses: actions/checkout@v2

      - name: Use Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Check formatting
        run: deno task fmt

      - name: Analyze code
        run: deno task lint

      - name: Load dependencies into local cache
        run: deno task cache

      - name: Run unit and integration tests
        run: deno task test

      - name: Generate coverage report
        # Only want to generate this once
        if: ${{ matrix.os.name == 'ubuntu-latest' }}
        run: deno task lcov

      - name: Compile executable for target ${{ matrix.os.target }}
        run: deno task compile --target ${{ matrix.os.target }} hello-gen.ts

      - name: Smoke test executable for target ${{ matrix.os.target }}
        run: ./hello-gen -h

      - name: Package executable
        if: startsWith(github.ref, 'refs/tags/')
        run: tar -czvf hello-gen-${{ github.ref_name }}-${{ matrix.os.platform }}-${{ matrix.os.cpu }}.tar.gz hello-gen

      - name: Upload package to release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: hello-gen-${{ github.ref_name }}-${{ matrix.os.platform }}-${{ matrix.os.cpu }}.tar.gz
